name: 'INVESTMENTS'
version: '1.0.0'
config-version: 2

profile: 'INVESTMENTS'

models:
  INVESTMENTS:
    raw:
      +schema: RAW
      +materialized: table
    staging:
      +schema: STAGING
      +materialized: table
    marts:
      +schema: PROD
      +materialized: table

seeds:
  INVESTMENTS:
    +schema: RAW

snapshots:
  INVESTMENTS:
    +schema: PROD
