name: 'INVESTMENTS'
version: '1.0.0'
config-version: 2

profile: 'INVESTMENTS'

# Model configuration
models:
  INVESTMENTS:                 # matches your root folder
    staging:
      +schema: STAGING       # absolute schema name; avoids RAW_STAGING
      +materialized: table
    marts:
      +schema: MARTS        # absolute schema name for marts
      +materialized: table

# Seeds configuration
seeds:
  INVESTMENTS:
    +schema: RAW               # seeds go to RAW schema
