create or replace database INVESTMENTS;

-------------------------------RAW LAYER-------------------------------

create or replace schema INVESTMENTS.RAW;

create or replace TABLE INVESTMENTS.RAW.RAW_ASSET_SEED (
	ASSET_CODE VARCHAR(16777216),
	ASSET_CODE_CURRENT VARCHAR(16777216),
	ASSET_NAME VARCHAR(16777216),
	CODE_SUFFIX VARCHAR(16777216),
	ASSET_TYPE VARCHAR(16777216)
);

create or replace TRANSIENT TABLE INVESTMENTS.RAW.RAW_ASSET (
	ASSET_CODE VARCHAR(16777216),
	ASSET_CODE_CURRENT VARCHAR(16777216),
	ASSET_NAME VARCHAR(16777216),
	CODE_SUFFIX VARCHAR(16777216),
	ASSET_TYPE VARCHAR(16777216),
    SOURCE_SYSTEM VARCHAR(19),
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE INVESTMENTS.RAW.RAW_ASSET_DETAILS (
	ASSET_CODE VARCHAR(50) NOT NULL,
	YF_ASSET_CODE VARCHAR(50),
	COUNTRY VARCHAR(100),
	SHORTNAME VARCHAR(500),
	LONGNAME VARCHAR(500),
	QUOTETYPE VARCHAR(50),
	SECTOR VARCHAR(200),
	INDUSTRY VARCHAR(200),
	CURRENCY VARCHAR(10),
	EXCHANGE VARCHAR(100),
	SOURCE_SYSTEM VARCHAR(100),
	LOAD_TS TIMESTAMP_NTZ(9)
);

CREATE OR REPLACE TABLE INVESTMENTS.RAW.RAW_ASSET_PRICES (
	ASSET_CODE VARCHAR(16777216),
	PRICE_DATE DATE,
	PRICE_OPEN NUMBER(10,2),
	PRICE_HIGH NUMBER(10,2),
	PRICE_LOW NUMBER(10,2),
	PRICE_CLOSE NUMBER(10,2),
	PRICE_ADJ_CLOSE NUMBER(10,2),
	PRICE_VOLUME NUMBER(38,0),
	CURRENCY VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE INVESTMENTS.RAW.RAW_EXCHANGE_RATES (
	CURRENCY_FROM VARCHAR(10) NOT NULL,
	CURRENCY_TO VARCHAR(10) NOT NULL,
	RATE_DATE DATE NOT NULL,
	EXCHANGE_RATE FLOAT,
	SOURCE_SYSTEM VARCHAR(50),
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (CURRENCY_FROM, CURRENCY_TO, RATE_DATE)
);

create or replace TABLE INVESTMENTS.RAW.RAW_TRANSACTIONS_CLEAR (
	"Entrada/Saída" VARCHAR(50),
	"Data" VARCHAR(20),
	"Movimentação" VARCHAR(200),
	"Produto" VARCHAR(500),
	"Instituição" VARCHAR(200),
	"Quantidade" VARCHAR(50),
	"Preço unitário" VARCHAR(50),
	"Valor da Operação" VARCHAR(50),
	SOURCE_FILE VARCHAR(500),
	SOURCE_SYSTEM VARCHAR(100),
	LOAD_TS TIMESTAMP_NTZ(9)
);
create or replace TABLE INVESTMENTS.RAW.RAW_TRANSACTIONS_XTB (
	ID VARCHAR(16777216),
	TYPE VARCHAR(16777216),
	TIME VARCHAR(16777216),
	COMMENT VARCHAR(16777216),
	SYMBOL VARCHAR(16777216),
	AMOUNT VARCHAR(16777216),
	SOURCE_FILE VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216) NOT NULL DEFAULT 'xtb_portugal',
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);



create or replace schema INVESTMENTS.STAGING;

create or replace TABLE INVESTMENTS.STAGING.STG_EXCHANGE_RATES (
	CURRENCY_FROM VARCHAR(10),
	CURRENCY_TO VARCHAR(10),
	RATE_DATE TIMESTAMP_NTZ(9),
	EXCHANGE_RATE NUMBER(10,4),
	SOURCE_SYSTEM VARCHAR(50),
	LOAD_TS TIMESTAMP_NTZ(9)
);

create or replace TABLE INVESTMENTS.STAGING.STG_STOCK_PRICES (
	TICKER VARCHAR(16777216),
	PRICE_DATE DATE,
	PRICE_OPEN NUMBER(10,2),
	PRICE_HIGH NUMBER(10,2),
	PRICE_LOW NUMBER(10,2),
	PRICE_CLOSE NUMBER(10,2),
	PRICE_ADJ_CLOSE NUMBER(10,2),
	PRICE_VOLUME NUMBER(38,0),
	CURRENCY VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9)
);
create or replace TABLE INVESTMENTS.STAGING.STG_ASSET (
	ASSET_CODE VARCHAR(16777216),
	ASSET_CODE_CURRENT VARCHAR(16777216),
	ASSET_NAME VARCHAR(16777216),
    ASSET_TYPE VARCHAR(16777216),
    CODE_SUFFIX VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(19),
	LOAD_TS TIMESTAMP_LTZ(9)
);
create or replace TABLE INVESTMENTS.STAGING.STG_ASSET_DETAILS (
	ASSET_CODE VARCHAR(150) NOT NULL,
	YAHOO_FINANCE_ASSET_CODE VARCHAR(50),
	ASSET_COUNTRY VARCHAR(100),
	SHORTNAME VARCHAR(16777216),
	QUOTETYPE VARCHAR(50),
	SECTOR VARCHAR(200),
	INDUSTRY VARCHAR(200),
	CURRENCY VARCHAR(10),
	EXCHANGE VARCHAR(100),
	SOURCE_SYSTEM VARCHAR(100),
	LOAD_TS TIMESTAMP_NTZ(9)
);
create or replace TABLE INVESTMENTS.STAGING.STG_TRANSACTIONS_XTB (
	TRANSACTION_ID NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(16777216),
	TRANSACTION_TIME TIMESTAMP_NTZ(9),
	TRANSACTION_COMMENT VARCHAR(16777216),
	TICKER VARCHAR(16777216),
	CURRENCY VARCHAR(3),
	AMOUNT NUMBER(10,2),
	SOURCE_FILE VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9)
);

create or replace schema INVESTMENTS.PROD;

create or replace TABLE INVESTMENTS.PROD.DIM_CURRENCY (
	CURRENCY_ID VARCHAR(16777216) NOT NULL,
	CURRENCY_ABRV VARCHAR(16777216) NOT NULL,
	CURRENCY_NAME VARCHAR(16777216) NOT NULL,
	LOAD_TS TIMESTAMP_NTZ(9) NOT NULL,
	DBT_UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL
);
create or replace TRANSIENT TABLE INVESTMENTS.PROD.DIM_DATE (
	DATE_ID NUMBER(38,0),
	DATE DATE,
	YEAR NUMBER(4,0),
	QUARTER_NUMBER NUMBER(2,0),
	MONTH_NUMBER NUMBER(2,0),
	MONTH_NAME VARCHAR(16777216),
	MONTH_ABRV VARCHAR(16777216),
	MONTH_ABRV_YEAR VARCHAR(16777216),
	DAY NUMBER(2,0),
	DAY_OF_WEEK NUMBER(2,0),
	DAY_NAME VARCHAR(3),
	WEEK_OF_YEAR NUMBER(2,0)
);

CREATE OR REPLACE TABLE PROD.DIM_ASSET (
    ASSET_ID VARCHAR(32) NOT NULL,
    ASSET_CODE VARCHAR(50) NOT NULL,
    ASSET_CODE_CURRENT VARCHAR(50),
    ASSET_NAME VARCHAR(255),
    ASSET_COUNTRY VARCHAR(100),
    INVESTMENT_COUNTRY VARCHAR(50),
    YAHOO_FINANCE_ASSET_CODE VARCHAR(50),
    SHORTNAME VARCHAR(255),
    QUOTETYPE VARCHAR(50),
    SECTOR VARCHAR(100),
    ASSET_TYPE VARCHAR(50),
    INDUSTRY VARCHAR(100),
    EXCHANGE VARCHAR(100),
    SOURCE_SYSTEM VARCHAR(50),
    LOAD_TS TIMESTAMP_NTZ
);

create or replace TABLE INVESTMENTS.PROD.DIM_TRANSACTION_TYPE (
	TRANSACTION_TYPE_ID VARCHAR(16777216),
	TRANSACTION_TYPE VARCHAR(16777216),
    TRANSACTION_TYPE_GROUP VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INVESTMENTS.PROD.FCT_EXCHANGE_RATES (
	RATE_DATE_ID NUMBER(38,0),
	CURRENCY_ID_FROM VARCHAR(16777216),
	CURRENCY_ID_TO VARCHAR(16777216),
	EXCHANGE_RATE NUMBER(10,4),
	SOURCE_SYSTEM VARCHAR(50),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TRANSIENT TABLE INVESTMENTS.PROD.FCT_PORTFOLIO_SNAPSHOTS_DAILY (
	DATE_ID NUMBER(38,0),
	TICKER_ID VARCHAR(32),
	QUANTITY NUMBER(12,4),
	AMOUNT NUMBER(12,2),
	PRICE_CURRENCY_ID VARCHAR(16777216),
	QUANTITY_CUMULATIVE NUMBER(24,4),
	AMOUNT_INVESTED_CUMULATIVE NUMBER(24,2),
	PORTFOLIO_VALUE_EUR NUMBER(10,2)
);
create or replace TABLE INVESTMENTS.PROD.FCT_STOCK_PRICES (
	TICKER_ID VARCHAR(16777216) NOT NULL,
	PRICE_DATE_ID NUMBER(8,0) NOT NULL,
	PRICE_OPEN FLOAT,
	PRICE_HIGH FLOAT,
	PRICE_LOW FLOAT,
	PRICE_CLOSE FLOAT NOT NULL,
	PRICE_ADJ_CLOSE FLOAT NOT NULL,
	PRICE_VOLUME NUMBER(38,0),
	PRICE_CURRENCY_ID VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TRANSIENT TABLE INVESTMENTS.PROD.FCT_TRANSACTIONS (
	TRANSACTION_ID NUMBER(38,0),
	TRANSACTION_DATE_ID NUMBER(38,0),
	TRANSACTION_TYPE_ID VARCHAR(16777216),
	TICKER_ID VARCHAR(32),
	CURRENCY_ID VARCHAR(16777216),
	QUANTITY NUMBER(11,4),
	PRICE NUMBER(10,2),
	AMOUNT NUMBER(11,2),
	COMMENT VARCHAR(16777216),
	SOURCE_FILE VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_NTZ(9)
);