{{
    config(
        materialized = 'incremental'
    ,   unique_key = 'symbol'
    ,   incremental_strategy = 'merge'
    )
}}

WITH cte_stock_info AS 
(
SELECT
    SYMBOL
,   SHORTNAME
,   LONGNAME
,   QUOTETYPE
,   SECTOR
,   INDUSTRY
,   CAST(FULLTIMEEMPLOYEES AS INT) AS FULLTIMEEMPLOYEES
,   CAST(MARKETCAP AS INT) AS MARKETCAP
,   CAST(DIVIDENDRATE AS NUMBER(10,2)) AS DIVIDENDRATE
,   CAST(DIVIDENDYIELD AS NUMBER(10,2)) AS DIVIDENDYIELD
,   CAST(BETA AS NUMBER(10,2)) AS BETA
,   CAST(TRAILINGPE AS NUMBER(10,2)) AS TRAILINGPE
,   CAST(FORWARDPE AS NUMBER(10,2)) AS FORWARDPE
,   CAST(FIFTYTWOWEEKHIGH AS NUMBER(10,2)) AS FIFTYTWOWEEKHIGH
,   CAST(FIFTYTWOWEEKLOW AS NUMBER(10,2)) AS FIFTYTWOWEEKLOW
,   CAST(REGULARMARKETPRICE AS NUMBER(10,2)) AS REGULARMARKETPRICE
,   CURRENCY
,   EXCHANGE
,   INFO_FETCH_DATE
,   SOURCE_SYSTEM
,   CAST(LOAD_TS AS TIMESTAMP) AS LOAD_TS
FROM {{source('raw','raw_stock_info')}}
)

SELECT * FROM cte_stock_info
