{{
    config(
        materialized = 'incremental'
    ,   unique_key = ['ASSET_CODE','PRICE_DATE']
    ,   on_schema_change = 'fail'
    )
}}

WITH asset_prices AS (
SELECT 
    UPPER(TRIM(ASSET_CODE)) AS ASSET_CODE
,   CAST(PRICE_DATE AS DATE) AS PRICE_DATE
,   CAST(PRICE_OPEN AS NUMBER(10,2)) AS PRICE_OPEN
,   CAST(PRICE_HIGH AS NUMBER(10,2)) AS PRICE_HIGH
,   CAST(PRICE_LOW AS NUMBER(10,2)) AS PRICE_LOW
,   CAST(PRICE_CLOSE AS NUMBER(10,2)) AS PRICE_CLOSE
,   CAST(PRICE_ADJ_CLOSE AS NUMBER(10,2)) AS PRICE_ADJ_CLOSE
,   CAST(PRICE_VOLUME AS INT) AS PRICE_VOLUME
,   UPPER(TRIM(CURRENCY)) AS CURRENCY
,   SOURCE_SYSTEM
,   CAST(LOAD_TS AS TIMESTAMP) AS LOAD_TS
FROM {{source('raw','raw_asset_prices')}}

{% if is_incremental() %}

    WHERE LOAD_TS > (SELECT COALESCE(MAX(LOAD_TS), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})

{% endif %}

)

SELECT * FROM asset_prices