create or replace TABLE RAW.RAW_EXCHANGE_RATES (
	CURRENCY_FROM VARCHAR(10) NOT NULL,
	CURRENCY_TO VARCHAR(10) NOT NULL,
	RATE_DATE DATE NOT NULL,
	EXCHANGE_RATE FLOAT,
	SOURCE_SYSTEM VARCHAR(50),
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (CURRENCY_FROM, CURRENCY_TO, RATE_DATE)
);