WITH CTE_STOCK_COUNTRY AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY STIN.SYMBOL) AS STOCK_ID,
        SPLIT_PART(STIN.SYMBOL, '.', 1) AS SYMBOL,
        STIN.SYMBOL AS ORIGINAL_SYMBOL,
        STIN.LONGNAME AS NAME,
        STIN.QUOTETYPE,
        CASE
            WHEN STIN.SECTOR = 'Real Estate' THEN 'REIT'
            WHEN STIN.QUOTETYPE = 'EQUITY' THEN 'STOCKS'
            WHEN STIN.QUOTETYPE = 'ETF' THEN QUOTETYPE
            ELSE 'OTHERS'
        END AS TYPE,
        STIN.SECTOR,
        STIN.INDUSTRY,
        STIN.CURRENCY,
        STIN.EXCHANGE,
        SCMA.COUNTRY_NAME,
        SCMA.CONTINENT,
        STIN.INFO_FETCH_DATE,
        STIN.SOURCE_SYSTEM,
        STIN.LOAD_TS,
        CURRENT_TIMESTAMP() AS DBT_CREATED_AT,
        CURRENT_TIMESTAMP() AS DBT_UPDATED_AT
    FROM {{ ref('stg_stock_info') }} STIN
    LEFT JOIN {{ ref('stg_stock_country_mapping') }} SCMA
        ON SCMA.SYMBOL = STIN.SYMBOL
)

SELECT * FROM CTE_STOCK_COUNTRY