SELECT
    SPLIT_PART(SYMBOL, '.', 1) AS SYMBOL,
    SYMBOL AS ORIGINAL_SYMBOL,
    LONGNAME AS NAME,
    QUOTETYPE,
    CASE
        WHEN SECTOR = 'Real Estate' THEN 'REIT'
        WHEN QUOTETYPE = 'EQUITY' THEN 'STOCKS'
        WHEN QUOTETYPE = 'ETF' THEN QUOTETYPE
        ELSE 'OTHERS'
    END AS TYPE,
    SECTOR,
    INDUSTRY,
    CURRENCY,
    EXCHANGE,
    INFO_FETCH_DATE,
    SOURCE_SYSTEM,
    LOAD_TS
FROM STAGING.STG_STOCK_INFO