SELECT
    ABS(HASH(STPR.TICKER, STPR.SOURCE_SYSTEM)) AS STOCK_PRICES_ID
,   TICK.TICKER_ID
,   TO_NUMBER(TO_VARCHAR(STPR.PRICE_DATE,'YYYYMMDD')) AS PRICE_DATE_KEY
,   STPR.PRICE_OPEN
,   STPR.PRICE_HIGH
,   STPR.PRICE_LOW
,   STPR.PRICE_CLOSE
,   STPR.PRICE_ADJ_CLOSE
,   STPR.PRICE_VOLUME
,   STPR.SOURCE_SYSTEM
,   STPR.LOAD_TS
,   CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS DBT_UPDATED_AT
FROM {{ref('stg_stock_prices')}} STPR

LEFT
JOIN {{ref('dim_ticker')}} TICK
ON TICK.ORIGINAL_TICKER = STPR.TICKER