create or replace TABLE INVESTMENTS.PROD.DIM_TRANSACTION_TYPE (
	TRANSACTION_TYPE_ID NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(16777216),
	SOURCE_SYSTEM VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_LTZ(9)
);