CREATE OR REPLACE TABLE INVESTMENTS.PROD.DIM_CURRENCY (
	CURRENCY_ID VARCHAR(16777216) NOT NULL,
	CURRENCY_ABRV VARCHAR(16777216) NOT NULL,
	CURRENCY_NAME VARCHAR(16777216) NOT NULL,
	LOAD_TS TIMESTAMP_NTZ(9) NOT NULL,
	DBT_UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL
);