CREATE OR REPLACE TABLE INVESTMENTS.PROD.DIM_TRANSACTION_TYPE (
	TRANSACTION_TYPE_ID VARCHAR(16777216),
	TRANSACTION_TYPE VARCHAR(16777216),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_LTZ(9)
);