CREATE OR REPLACE TABLE INVESTMENTS.PROD.FCT_STOCK_PRICES (
    TICKER_ID           VARCHAR(16777216)   NOT NULL,
    PRICE_DATE_ID       NUMBER(8,0)    NOT NULL,  
    PRICE_OPEN          FLOAT,
    PRICE_HIGH          FLOAT,
    PRICE_LOW           FLOAT,
    PRICE_CLOSE         FLOAT NOT NULL,
    PRICE_ADJ_CLOSE     FLOAT NOT NULL,
    PRICE_VOLUME        NUMBER(38,0),
    SOURCE_SYSTEM       STRING,
    LOAD_TS             TIMESTAMP_NTZ(9),
    DBT_UPDATED_AT      TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);