CREATE OR REPLACE TABLE INVESTMENTS.PROD.FCT_EXCHANGE_RATES (
	RATE_DATE_ID NUMBER(38,0),
	CURRENCY_ID_FROM VARCHAR(16777216),
	CURRENCY_ID_TO VARCHAR(16777216),
	EXCHANGE_RATE NUMBER(10,4),
	SOURCE_SYSTEM VARCHAR(50),
	LOAD_TS TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_NTZ(9)
);