CREATE OR REPLACE TABLE PROD.FCT_STOCK_PRICES (
    STOCK_PRICES_ID     NUMBER(38,0)   PRIMARY KEY,
    TICKER_ID           NUMBER(38,0)   NOT NULL,
    PRICE_DATE_KEY      NUMBER(8,0)    NOT NULL,  
    PRICE_OPEN          FLOAT,
    PRICE_HIGH          FLOAT,
    PRICE_LOW           FLOAT,
    PRICE_CLOSE         FLOAT,
    PRICE_ADJ_CLOSE     FLOAT,
    PRICE_VOLUME        NUMBER(38,0),
    SOURCE_SYSTEM       STRING,
    LOAD_TS             TIMESTAMP_NTZ(9),
    DBT_UPDATED_AT      TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
