CREATE OR REPLACE TABLE INVESTMENTS.PROD.FCT_TRADES (
    TRADE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    TRANSACTION_ID VARCHAR(100) NOT NULL,  -- Add the natural key
    TRANSACTION_DATE_KEY NUMBER(38,0) NOT NULL,
    TRANSACTION_TYPE_ID NUMBER(18,0) NOT NULL,
    TICKER_ID NUMBER(19,0) NOT NULL,
    CURRENCY_ID NUMBER(38,0) NOT NULL,
    QUANTITY NUMBER(10,4),
    PRICE NUMBER(10,2),
    AMOUNT NUMBER(11,2),
    COMMENT VARCHAR(16777216),
    SOURCE_FILE VARCHAR(16777216),
    SOURCE_SYSTEM VARCHAR(16777216) NOT NULL,
    LOAD_TS TIMESTAMP_NTZ(9) NOT NULL,
    DBT_UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL
);