create or replace TABLE INVESTMENTS.STAGING.STG_EXCHANGE_RATES (
	CURRENCY_FROM VARCHAR(10),
	CURRENCY_TO VARCHAR(10),
	RATE_DATE TIMESTAMP_NTZ(9),
	EXCHANGE_RATE NUMBER(10,4),
	SOURCE_SYSTEM VARCHAR(50),
	LOAD_TS TIMESTAMP_NTZ(9)
);