version: 2

sources:
  - name: raw 
    database: INVESTMENTS
    schema: RAW
    tables:
      - name: raw_transactions_pt
        identifier: RAW_TRANSACTIONS_PT
        description: "Raw transactions from XTB"
        freshness:
          warn_after: {count: 35, period: day}
          error_after: {count: 45, period: day}
        loaded_at_field: LOAD_TS

      - name: raw_stock_prices
        identifier: RAW_STOCK_PRICES
        description: "Daily stock prices from Yahoo Finance"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: LOAD_TS

      - name: raw_symbol
        identifier: RAW_SYMBOL
        description: "Stock descriptive information such as field, area of business..."

      - name: raw_exchange_rates
        identifier: RAW_EXCHANGE_RATES
        description: "Daily exchange rates for USD, BRL and GBP to EUR"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: LOAD_TS

      - name: raw_stock_country_mapping
        identifier: RAW_STOCK_COUNTRY_MAPPING
        description: "Mapping from which countries/continents the symbol comes from"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: LOAD_TS
